name: nimble
description: A fast online chat app.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.1

  #Firebase
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5

  #Alerts
  rflutter_alert: ^1.0.3

  #Modal Progress HUD
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-Regular.ttf
        - asset: fonts/Nunito/Nunito-Bold.ttf
        - asset: fonts/Nunito/Nunito-Black.ttf
          weight: 900

